<?php

/*
 $course_id = $_GET['video'];
$notify_update = $this->db->where('nodification_to', $_SESSION['Email']);
$notify_update = $this->db->where('nodification_for', $course_id);
$notify_update = $this->db->update('nodification', array('nodification_status'=> 0));
*/


?>
<!-- #region Jssor Slider Begin -->

<!-- Generated by Jssor Slider Maker Online. -->
<!-- This demo works without jquery library. -->

<script type="text/javascript" src="<?= base_url(); ?>assets/js/jssor.slider.min.js"></script>

<!-- use jssor.slider.debug.js instead for debug -->
<script>
    jssor_1_slider_init = function () {

        var jssor_1_options = {
            $AutoPlay: false,
            $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
            },
            $ThumbnailNavigatorOptions: {
                $Class: $JssorThumbnailNavigator$,
                $Cols: 4,
                $SpacingX: 4,
                $SpacingY: 4,
                $Orientation: 2,
                $Align: 0
            }
        };

        var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

        //responsive code begin
        //you can remove responsive code if you don't want the slider scales while window resizing
        function ScaleSlider() {
            var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
            if (refSize) {
                refSize = Math.min(refSize, 810);
                jssor_1_slider.$ScaleWidth(refSize);
            } else {
                window.setTimeout(ScaleSlider, 30);
            }
        }
        ScaleSlider();
        $Jssor$.$AddEvent(window, "load", ScaleSlider);
        $Jssor$.$AddEvent(window, "resize", $Jssor$.$WindowResizeFilter(window, ScaleSlider));
        $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
        //responsive code end
    };
</script>
<script type="text/javascript">
    function show(dw) {
        document.getElementById(dw).style.display = 'block';

    }
</script>
<style type="text/css">
    .content{
        display:none;

    }
    #anchor
    {
        pointer-events:none;
    }
	#main_iframe iframe{
		
			width: 800px;
			height:400px;
			
			}
			
		 	 

			
</style>

<style>

    /* jssor slider arrow navigator skin 02 css */
    /*
    .jssora02l                  (normal)
    .jssora02r                  (normal)
    .jssora02l:hover            (normal mouseover)
    .jssora02r:hover            (normal mouseover)
    .jssora02l.jssora02ldn      (mousedown)
    .jssora02r.jssora02rdn      (mousedown)
    */
    .jssora02l, .jssora02r {
        display: block;
        position: absolute;
        /* size of arrow element */
        width: 55px;
        height: 55px;
        cursor: pointer;
        background: url('img/a02.png') no-repeat;
        overflow: hidden;
    }
    .jssora02l { background-position: -3px -33px; }
    .jssora02r { background-position: -63px -33px; }
    .jssora02l:hover { background-position: -123px -33px; }
    .jssora02r:hover { background-position: -183px -33px; }
    .jssora02l.jssora02ldn { background-position: -3px -33px; }
    .jssora02r.jssora02rdn { background-position: -63px -33px; }
    /* jssor slider thumbnail navigator skin 11 css *//*.jssort11 .p            (normal).jssort11 .p:hover      (normal mouseover).jssort11 .pav          (active).jssort11 .pav:hover    (active mouseover).jssort11 .pdn          (mousedown)*/.jssort11 .p {    position: absolute;    top: 0;    left: 0;    width: 200px;    height: 69px;    background: #181818;}.jssort11 .tp {    position: absolute;    top: 0;    left: 0;    width: 100%;    height: 100%;    border: none;}.jssort11 .i, .jssort11 .pav:hover .i {    position: absolute;    top: 3px;    left: 3px;    width: 60px;    height: 30px;    border: white 1px dashed;}* html .jssort11 .i {    width /**/: 62px;    height /**/: 32px;}.jssort11 .pav .i {    border: white 1px solid;}.jssort11 .t, .jssort11 .pav:hover .t {    position: absolute;    top: 3px;    left: 68px;    width: 129px;    height: 32px;    line-height: 32px;    text-align: center;    color: #fc9835;    font-size: 13px;    font-weight: 700;}.jssort11 .pav .t, .jssort11 .p:hover .t {    color: #fff;}.jssort11 .c, .jssort11 .pav:hover .c {    position: absolute;    top: 38px;    left: 3px;    width: 197px;    height: 31px;    line-height: 31px;    color: #fff;    font-size: 11px;    font-weight: 400;    overflow: hidden;}.jssort11 .pav .c, .jssort11 .p:hover .c {    color: #fc9835;}.jssort11 .t, .jssort11 .c {    transition: color 2s;    -moz-transition: color 2s;    -webkit-transition: color 2s;    -o-transition: color 2s;}.jssort11 .p:hover .t, .jssort11 .pav:hover .t, .jssort11 .p:hover .c, .jssort11 .pav:hover .c {    transition: none;    -moz-transition: none;    -webkit-transition: none;    -o-transition: none;}.jssort11 .p:hover, .jssort11 .pav:hover {    background: #333;}.jssort11 .pav, .jssort11 .p.pdn {    background: #462300;}

</style>

<body>

    
        <section class="wrapper">

            <div class="row">
                <div class="row mt" style="padding-bottom:215px;">
                    <div class="col-lg-12">
                        <div class="site-wrapper">
                            <div class="site-wrapper-inner">
                                <div class="cover-container">
                                    <div class="col-md-12">

                                        <div class="row">
                                            <div class="box">
                                                <div class="col-lg-12">
                                                    <br>
                                                    <br>
                                                    <br>


                                                    <div style="border: 1px solid #ccc;margin:0 auto;" class="jumbotron col-sm-12">
                                                        <div class="row">
                                                            <div class="col-sm-8"><?php
															
															
																$this->load->model("InstructorModel");

																$teach_model= new InstructorModel();
																$this->load->model("Usermodel");

																$stud_model= new Usermodel();
																
																 $id = $this->input->get('id', TRUE);

																$main_vid = $teach_model->getLecInfo($id);
																	
																	
                                                                 $video = $main_vid['course'];

                                                                $query = $this->db->get_where('video_lectures', array('course' => $this->input->get('video')));



                                                                 $query_lec = $this->db->get_where('video_lectures', array('lec_video_id' => $id));
																 
																 
															

																

 
                                                                    ?>
                                                                   
                                                                    <div class="thumbnail" id = "main_iframe">
																		
																		
																			
																<?php echo $main_vid['embed_url']; ?>

                                                                    </div> 
                                                                
                                                            </div>
                                                            <div class="col-sm-3" style="overflow-y:scroll; margin-left: 50px; height: 500px;">
															
                                                                     <?php

 
 																	$course_info = $teach_model->getCourseInfo($video);
																	
 														 
																	$rel_vids = $teach_model->loadLecturesFromCourse($video);
																	 
                                                                    foreach ($rel_vids as $videos) {
                                                                        $id_rel_vid = $videos['lec_video_id'];

                                                                        ?>
                                                                         
                                                                              
                                                                                <div class="thumbnail rel_vids" <?php  if($id == $videos['lec_video_id']) { ?> style="background-color: Orange; " <?php } ?>>

                                                                                    <a href="<?php echo 'cont_presentation?id='.$id_rel_vid; ?>">
																					
																					<img style ="height: 100px; width: 250px;" src=  "<?php echo base_url().'/course_imgs/'.$course_info['courseID'].$course_info['course_image']; ?>" alt= "No Preview Available" >
																					
																					<?php echo $videos['lec_title']; ?>
																					
																					</a>
																					
                                                                                </div>
                                                                     <?php } ?>
                                                             </div>
                                                        </div>

                                                    </div> <!-- end of jumbotron -->
                                                            
                                                    <div style="border: 1px solid #ccc; margin:0 auto;  background-color: #fff;" class="col-sm-12" >
                                                        <?php

                                                         
                                                                
                                                                ?>
                                                            <h2><b><?php echo $main_vid['lec_title']; ?><b>
															
															
															</h2>
                                                            <h4>Date Uploaded: <?php 
																										
											$date_enrolled_format= strtotime($main_vid['date_uploaded']);
											
												echo date("M d, Y", $date_enrolled_format);
											
															?> </h4>
			
			<?php if($this->session->userdata('log_type') == "student" && $stud_model->check_lec_view($this->session->userdata('username'), $id) == 0){?>
															
<p class = 'text-info sm'>*Click the button after watching</p>
																												
<form action= "insert_lec_view" method = "POST">

		<input type = "submit" class = "btn btn-success" value = "I'm Done!" />
		<input type = "hidden"  value = "<?php echo $id; ?>" name = "video_lec_Id" />
	
</form>
			<?php } ?>
			
			<a href= "<?php echo 'presentation?id='.$course_info['courseID']; ?>" class = "btn btn-info">Back To Course</a>
                                                        
                                                        <br>
                                                        
														<?php
														
                                                        $course_id = $video;
                                                        $insert_data['quiz_taken_user_id'] = $this->session->userdata('Stud_Id');
                                                        $insert_data['quiz_taken_course_id'] = $course_id;
                                                        
                                                        ?>

                                                        <input type = "hidden" id = "course_id" name = "course_id" value = "<?php echo $course_id; ?>"/>
                                                        <div style="padding-bottom: 10px;" class="pull-right">

                                                            <?php 

																$this->load->model('InstructorModel');
																$teach_model = new InstructorModel();

																//* Load Quizzes in this Lecture...

																
																 $quizzes= $teach_model->loadQuizzes($this->input->get('id'));

																 
																 
																//print_r($quizzes);
																if($this->session->userdata('log_type')=== "student"){
																	
																foreach($quizzes as $row_quiz_info){
																	
																	if($teach_model->check_quiztaken($row_quiz_info['quiz_id'], $this->session->userdata('username')) == 0){
																	 ?>
																	 
																   <a href="<?php echo site_url('IM/quizinstruction?quiz_id=' . $row_quiz_info['quiz_id']); ?>"> <button type="button" class="btn btn-primary btn-lg">Take Quiz 
																   <?php echo $row_quiz_info['quiz_name']; ?>
																   </a>

																   
                                                            
															<?php }
																else {
																	
																	?>
																	
																	  <a href="<?php echo site_url('IM/ViewQuiz?quiz_id=' . $row_quiz_info['quiz_id']); ?>"> <button type="button" class="btn btn-info btn-lg">
																	  View Quiz Result Here
																		</a>
																	<?php 
																}
															}
														}
															?>														
															
															
															
															
                                                        </div>


                                                    </div>
                                                </div> <!-- end of box -->
                                            </div> <!-- end of row -->


                                            <div class="col-sm-12" style="position:relative; margin:auto;padding-top:20px;">
                                                <div class="row">
                                                    <div class="board col-sm-10" style="padding-left:15%;" >

                                                        <div class="board-inner">
                                                            <ul class="nav nav-tabs" id="myTab">
                                                                <div class="liner"></div>



                                                                <li><a href="#messages" data-toggle="tab" title="bootsnipp goodies">
                                                                        <span class="round-tabs three">
                                                                            <i class="glyphicon glyphicon-comment"></i>
                                                                        </span> </a>
                                                                </li>

                                                                <li><a href="#settings" data-toggle="tab" title="blah blah">
                                                                        <span class="round-tabs four">
                                                                            <i class="glyphicon glyphicon-bullhorn"></i>
                                                                        </span> 
                                                                    </a></li>

                                                                <li><a href="#doner" data-toggle="tab" title="completed">
                                                                        <span class="round-tabs five">
                                                                            <i class="glyphicon glyphicon-folder-open"></i>
                                                                        </span> </a>


                                                                </li>

                                                            </ul></div>

                                                        <div class="tab-content">
                                                      
                                                            <div class="tab-pane fade" id="profile">
                                                                <h3 class="head text-center">Create a Bootsnipp<sup>™</sup> Profile</h3>
                                                                <p class="narrow text-center">
                                                                    Lorem ipsum dolor sit amet, his ea mollis fabellas principes. Quo mazim facilis tincidunt ut, utinam saperet facilisi an vim.
                                                                </p>

                                                                <p class="text-center">
                                                                    <a href="" class="btn btn-success btn-outline-rounded green"> create your profile <span style="margin-left:10px;" class="glyphicon glyphicon-send"></span></a>
                                                                </p>

                                                            </div>

                                                            <div class="tab-pane fade" id="doner">

                                                               <h3 class="head text-center">Download Your Notes.<span style="color:#f48260;">♥</span> </h3>
                                                               
                                                                    <label><h4><?php echo $main_vid['lecture_name']; ?></h4></label>
                                                                    <a href="<?php echo 'download_lec?id='. $main_vid['lec_video_id']; ?>" class= "btn btn-success pull-right"> Download</a>
                                                                
                                                            
                                                                
                                                           
                                                                </div>

                                                               <script>
                                                               /*
                                                               $(document).ready(function(){



                                                               });
*/
                                                               </script>

                                                            <div class="tab-pane fade in active" id="messages" style= "visibility:visible;">
                                                                <form action="sd">
                                                                    <h3 class="head text-center">Discussion Board</h3>
                                                                    <input type="text" class="hidden" value="<?= $this->input->get('id') ?>" name="lec_video_id" id="lec_video_id">
                                                                    <textarea class="discussion_comment col-sm-12" name="discussion_comment" id="discussion_comment" style="resize:none; height:100px;"></textarea>
                                                                    <p class="text-center insert_comment" id="insert_comment" >
                                                                        <a href="javascript:void(0)"  style="margin-top:15px;" class=" btn btn-success btn-outline-rounded green" id = "add_discuss"> Add Discussion<span style="margin-left:10px; margin-top:" class="glyphicon glyphicon-send"></span></a>
                                                                    </p>
                                                                </form>




                                                                <div class="container active">
                                                                    <div class="row">
                                                                        <div class="col-md-8">
                                                                            <h2 class="page-header">Comments</h2>
                                                                            <section class="comment-list">
                                                                                <!-- Start Comment -->
                                                                                <?php $this->load->view('presentation/comments_view'); ?>                                                                                                                                                                                                                                    

                                                                            </section>
                                                                        </div>
                                                                    </div>
                                                                </div>

                                                            </div>
                                                            <div class="tab-pane fade" id="settings">
                                                                <h3 class="head text-center">Announcements!</h3>
                                                                <div class="container">
                                                                    <div class="row">
                                                                        <div class="col-md-8">

                                                                            <section class="comment-list">
                                                                                <!-- First Comment -->
                                                                                <?php
                                                                                $announcements = $this->comments->get_announcement($this->input->get('video'));
                                                                                foreach ($announcements as $announcement) {
                                                                                    ?>
                                                                                    <article class="row">
                                                                                        <div class="col-md-2 col-sm-2 hidden-xs">
                                                                                            <figure class="thumbnail">
                                                                                                <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
                                                                                                <figcaption class="text-center"><?= $announcement->Username ?></figcaption>
                                                                                            </figure>
                                                                                        </div>
                                                                                        <div class="col-md-10 col-sm-10">
                                                                                            <div class="panel panel-default arrow left">
                                                                                                <div class="panel-body">
                                                                                                    <header class="text-left">
                                                                                                        <div class="comment-user"><i class="fa fa-user"></i> <?= $announcement->Fname . ' ' . $announcement->Lname ?></div>
                                                                                                        <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i>&nbsp;<?= date('l d, Y', strtotime($announcement->announcement_date_createdby)) ?></time>
                                                                                                    </header>
                                                                                                    <div class="comment-post">
                                                                                                        <h3><?= $announcement->announcement_title ?></h3>
                                                                                                        <p>
                                                                                                            <?= $announcement->announcement_content ?>
                                                                                                        </p>
                                                                                                    </div>
                                                                                                   <!-- <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p>-->
                                                                                                </div>
                                                                                            </div>
                                                                                        </div>
                                                                                    </article>
                                                                                <?php } ?>
                                                                                <!-- End  -->
                                                                            </section>
                                                                        </div>
                                                                    </div>
                                                                </div>


                                                            </div>
                                                            <div class="tab-pane fade" id="doner">
                                                                <div class="text-center">
                                                                    <i class="img-intro icon-checkmark-circle"></i>
                                                                </div>
                                                               
                                                            </div> <!-- end fo tab fane -->

                                                            <div class="clearfix"></div>
                                                        </div>

                                                    </div>
                                                </div>
                                            </div>





                                        </div> <!-- end of col-md-12 -->
                                    </div> <!-- end of cover-container-->
                                </div> <!-- end of site wrapper container -->
                            </div> <!-- site wrapper -->
                        </div> <!-- col lg 12-->
                    </div> <!-- / row mt -->
                </div><!-- /row -->
        </section>
    


    <!--- by gml -->



</body>
<script type="text/javascript" src="<?= base_url(); ?>js/jquery.min.js"></script>
<script type="text/javascript" src="<?= base_url(); ?>js/video.js"></script>
<script>
var reply_comment_id,  form_id;

    $(function () {
        $("#add_discuss").click(function ()
        {

            var comment = $(this).parent('form').find(".discussion_comment").val();
            var article_id = '<?= $this->input->get('lec_video_id', true) ?>';
            var dataString = 'discussion_comment=' + comment + '&article_id=' + article_id;
            

            if (comment == '')
            {
                alert('Please Fill the Comment');
            } else
            {
                
                $.post("insert_comments", {

                 lec_video_id: $("#lec_video_id").val(),

                 discussion_comment: $("#discussion_comment").val(),

                 course_id: $("#course_id").val()


                }, function(data){


                location.href= location.href;

                alert("Comment Has Been Added! Refresh to see comment!");

                });


                /* $.ajax({
                    type: "POST",
                    url: "<?php echo base_url(); ?>index.php/IM/insert_comments/",
                    data: $(this).parent('form').serialize(),
                    cache: false,
                    success: function (data) {
                        console.log(data);
                        data = JSON.parse(data);
                        if (data.st == 0)
                        {
                            alert(data.msg);
                        }

                        if (data.st == 1)
                        {
                            alert(data.msg);
                            location.reload();
                        }
                    },
                    error: function (data) {
                        alert('Please try again');
                    }
                }); */


            }
            return false;

        });

        $(".reply_comment_btn").click(function ()
        {
            var form_id = $(this).attr('data-id');
            $(this).parent().parent().find('form').parent('div#reply' + form_id).show('slow');
            //$('#' + form_id).show('slow');
        });
        $(".edit_comment_btn").click(function ()
        {
            var form_id = $(this).attr('data-id');
            var update_id = $(this).attr('data-comment');
            $('#insert_reply_comment' + form_id).removeClass('insert_reply_comment').addClass('insert_comment');
            var update_input = '<input type="hidden" name="update_id" value="' + update_id + '" id="update_id">';
            var comments = $(this).parent().parent().find('.comment-post p').html();
            //$(this).parent().parent().find('form #').
            $(this).parent().parent().find('form').parent('div#edit' + form_id).show('slow');
            $(this).parent().parent().find('form').append(update_input);
            $(this).parent().parent().find('textarea').val(comments.trim());
            //$('#' + form_id).show('slow');
        });
        $(".edit_comment_reply_btn").click(function ()
        {
            var form_id = $(this).attr('data-id');
            var update_id = $(this).attr('data-reply');
            var update_input = '<input type="hidden" name="update_id" value="' + update_id + '" id="update_id">';
            var comments = $(this).parent().parent().find('.comment-post p').html();
            $(this).parent().parent().find('form').parent('div#reply' + form_id).show('slow');
            $(this).parent().parent().find('form').append(update_input);
            $(this).parent().parent().find('textarea').val(comments.trim());
            //$('#' + form_id).show('slow');
        });
        $(".delete_comment_btn").click(function ()
        {
            var article_id = $(this).attr('data-id');
            var table_case = $(this).attr('data-case');
            //="reply_comments"         
            if (confirm('Did you want to delete this comment')) {
                $.ajax({
                    type: "POST",
                    url: "<?php echo base_url(); ?>index.php/IM/delete_comments/",
                    data: 'case=' + table_case + '&article_id=' + article_id,
                    cache: false,
                    success: function (data) {
                        console.log(data);
                        data = JSON.parse(data);
                        if (data.st == 0)
                        {
                            alert(data.msg);
                        }

                        if (data.st == 1)
                        {
                            $('#article_' + article_id).fadeOut('slow').remove();
                            $('.reply_article_' + article_id).fadeOut('slow').remove();
                            alert(data.msg);
                        }
                    },
                    error: function (data) {
                        alert('Please try again');
                    }
                });
            }

        });

        $(".insert_reply_comment").click(function ()
        {
             form_id = $(this).attr('data-id');
             


            //reply_comment_id = $(this).attr('id');

            $("#display_comment").fadeIn(100).html('<img src="<?php echo base_url(); ?>uploads/ajax-loader.gif" />Loading Comment...');
            $.ajax({
                type: "POST",
                url: "<?php echo base_url(); ?>index.php/IM/insert_reply_comments/",
                data: $(this).parent('form').serialize(),
                cache: false,
                success: function (data) {

                    console.log(data);
                    data = JSON.parse(data);



                    if (data.st == 0)
                    {
                        alert(data.msg);
                    }

                    if (data.st == 1)
                    {


                        //$("#article_"+form_id).append(data);

                        alert("Reply Submitted!");


                    }

                    //* $("#article_"+form_id).append(data);

                },

                error: function (data) {
                    alert('Please try again');
                }
            });

            return false;

        });
    });

</script>